### ISSUE TITLE
Print tool - if you create too many PDF's, clear button disappears

### ISSUE THREAD

**Issue by LaurenMcArtney** [LocalMaps/LocalMaps#19]
In the print dialog, if you create enough PDFs, the Clear Maps button disappears off the bottom of the page, so you can’t clear them! 

Recommendation:
Probably best to have the button above the maps, or have some kind of scrolling window instead?

**Comment by carg563** [comment]
I can do this, but realistically, how many prints do we expect a user to create in a session?

**Comment by carg563** [comment]
Ok done, the print button appears above the prints now, so should not be overwritten.

**Comment by LaurenMcArtney** [comment]
Cool thanks! Also just thought I'd let you know, all these issues are directly from our **very** thorough support team testers (who often test beyond the probable amount of an average user...). This might explain some of the more unrealistic scenarios logged :)
